### ISSUE TITLE
Error not caught

### ISSUE THREAD

**Issue by Neil674** [Ananth09/frontend#4]
Modification in the try catch block

try {
  const response = await fetch(apiUrl, requestOptions);

  if (!response.ok) {
    throw new Error(`HTTP error! Status: ${response.status}`);
  }

  const result = await response.text();
  responseContainer.textContent = result;
} catch (error) {
  console.error("Error:", error.message || error);
  responseContainer.textContent = "An error occurred. Please try again.";
}

**Comment by Ananth09** [comment]
Thank you for your inputs @Neil674
